# Generated by Django 5.0.6 on 2024-05-26 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(max_length=20)),
                ('citizen_type', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=3)),
                ('disability', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=20)),
                ('permanent_province', models.CharField(max_length=50)),
                ('permanent_district', models.CharField(max_length=50)),
                ('permanent_address', models.TextField()),
                ('current_province', models.CharField(max_length=50)),
                ('current_district', models.CharField(max_length=50)),
                ('current_address', models.TextField()),
                ('user_profile_img', models.ImageField(upload_to='uploads/backimg/')),
                ('id_front_side', models.ImageField(upload_to='uploads/backimg/')),
                ('id_back_side', models.ImageField(upload_to='uploads/backimg/')),
                ('psid', models.CharField(default='', editable=False, max_length=8, unique=True)),
                ('pystatus', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
