# Generated by Django 5.0.6 on 2024-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_changepassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='learning_materials/')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
