# Generated by Django 5.0.6 on 2024-05-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_learningmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(upload_to='uploads/learning_materials/'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='icon',
            field=models.ImageField(upload_to='uploads/learning_materials/icons/'),
        ),
    ]
